import subprocess
import sys
import os
import platform
import numpy as np

# ─────────────────────────────────────────────
#  Colours (no dependencies needed)
# ─────────────────────────────────────────────
RESET = "\033[0m"
BOLD = "\033[1m"
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
DIM = "\033[2m"


def c(color, text):
    return f"{color}{text}{RESET}"


def header(text):
    print(
        f"\n{BOLD}{CYAN}{'─'*52}{RESET}\n{BOLD}{CYAN}  {text}{RESET}\n{BOLD}{CYAN}{'─'*52}{RESET}"
    )


def ok(text):
    print(f"  {GREEN}✓{RESET}  {text}")


def warn(text):
    print(f"  {YELLOW}⚠{RESET}  {text}")


def err(text):
    print(f"  {RED}✗{RESET}  {text}")


def info(text):
    print(f"  {DIM}→{RESET}  {text}")


def ask(prompt, default=""):
    val = input(
        f"  {CYAN}?{RESET}  {prompt}{f' [{default}]' if default else ''}: "
    ).strip()
    return val if val else default


# ─────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────

# scripts/setup.py → ROOT is one level up
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IS_WIN = platform.system() == "Windows"


def run(cmd, cwd=None, capture=False):
    try:
        result = subprocess.run(
            cmd, cwd=cwd or ROOT, shell=IS_WIN, capture_output=capture, text=True
        )
        return result.returncode == 0, result.stdout, result.stderr
    except FileNotFoundError:
        return False, "", "command not found"


def pip_install(packages: list):
    ok_flag, _, _ = run(
        [sys.executable, "-m", "pip", "install", "--upgrade", *packages]
    )
    return ok_flag


def read_env():
    env_path = os.path.join(ROOT, "config", ".env")
    existing = {}
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    existing[k.strip()] = v.strip()
    return existing


def write_env(data: dict):
    env_path = os.path.join(ROOT, "config", ".env")
    os.makedirs(os.path.dirname(env_path), exist_ok=True)
    with open(env_path, "w") as f:
        f.write("# JARVIS Configuration — generated by setup.py\n\n")
        for k, v in data.items():
            f.write(f"{k}={v}\n")


# ─────────────────────────────────────────────
#  STEP 1 — Python version check
# ─────────────────────────────────────────────
def check_python():
    header("STEP 1 — Python Version")
    major, minor = sys.version_info[:2]
    if major < 3 or minor < 10:
        err(f"Python 3.10+ required. You have {major}.{minor}.")
        err("Download from https://python.org")
        sys.exit(1)
    ok(f"Python {major}.{minor} detected")


# ─────────────────────────────────────────────
#  STEP 2 — Python dependencies
# ─────────────────────────────────────────────
def install_python_deps():
    header("STEP 2 — Python Dependencies")

    req_path = os.path.join(ROOT, "requirements.txt")
    if not os.path.exists(req_path):
        err("requirements.txt not found at project root.")
        sys.exit(1)

    info("Installing requirements.txt ...")
    success, _, stderr = run([sys.executable, "-m", "pip", "install", "-r", req_path])
    if not success:
        err(f"pip install failed:\n{stderr}")
        sys.exit(1)
    ok("requirements.txt installed")

    # pyaudio needs special treatment on Windows
    if IS_WIN:
        info("Checking pyaudio (Windows needs special install)...")
        try:
            import pyaudio

            ok("pyaudio already installed")
        except ImportError:
            warn("pyaudio not found — trying pipwin...")
            pip_install(["pipwin"])
            success, _, _ = run([sys.executable, "-m", "pipwin", "install", "pyaudio"])
            if success:
                ok("pyaudio installed via pipwin")
            else:
                warn("pyaudio install failed. Voice input may not work.")
                warn("Manual fix: pip install pipwin && pipwin install pyaudio")

    # opencv-contrib needed for face LBPH recognizer
    info("Checking opencv-contrib-python...")
    try:
        import cv2

        if not hasattr(cv2, "face"):
            warn("opencv-python found but missing contrib. Fixing...")
            pip_install(["--force-reinstall", "opencv-contrib-python"])
            ok("opencv-contrib-python installed")
        else:
            ok("opencv-contrib-python already installed")
    except ImportError:
        pip_install(["opencv-contrib-python"])
        ok("opencv-contrib-python installed")


# ─────────────────────────────────────────────
#  STEP 3 — Node.js + frontend build
# ─────────────────────────────────────────────
def build_frontend():
    header("STEP 3 — Frontend (React / Vite)")

    node_ok, node_ver, _ = run(["node", "--version"], capture=True)
    if not node_ok:
        err("Node.js not found.")
        err("Download from https://nodejs.org (LTS version)")
        sys.exit(1)
    ok(f"Node.js {node_ver.strip()} detected")

    npm_ok, npm_ver, _ = run(["npm", "--version"], capture=True)
    if not npm_ok:
        err("npm not found. Reinstall Node.js.")
        sys.exit(1)
    ok(f"npm {npm_ver.strip()} detected")

    frontend_dir = os.path.join(ROOT, "frontend")
    if not os.path.exists(frontend_dir):
        err("frontend/ directory not found.")
        sys.exit(1)

    info("Running npm install (this may take a minute)...")
    success, _, stderr = run(["npm", "install"], cwd=frontend_dir)
    if not success:
        err(f"npm install failed:\n{stderr}")
        sys.exit(1)
    ok("npm packages installed")

    info("Building frontend with Vite...")
    success, _, stderr = run(["npm", "run", "build"], cwd=frontend_dir)
    if not success:
        err(f"Vite build failed:\n{stderr}")
        sys.exit(1)

    dist_index = os.path.join(frontend_dir, "dist", "index.html")
    if not os.path.exists(dist_index):
        err("Build finished but dist/index.html not found.")
        sys.exit(1)
    ok("Frontend built → frontend/dist/")


# ─────────────────────────────────────────────
#  STEP 4 — .env configuration
# ─────────────────────────────────────────────
def configure_env():
    header("STEP 4 — Configuration (.env)")

    existing = read_env()

    if existing:
        warn(".env already exists — will update only fields you fill in.")

    print()
    print(f"  {DIM}Press Enter to skip any field you don't need yet.{RESET}")
    print()

    def prompt_field(key, label, default="", secret=False):
        current = existing.get(key, default)
        display = f"{'*' * len(current)}" if (secret and current) else current
        prompt_str = f"{label}{f' (current: {display})' if current else ''}"
        val = ask(prompt_str, current)
        existing[key] = val

    prompt_field(
        "OPENWEATHER_API_KEY", "OpenWeather API key  →  https://openweathermap.org/api"
    )
    prompt_field("DEFAULT_CITY", "Default city for weather", "Calgary")
    prompt_field("EMAIL_ADDRESS", "Gmail address for email skill")
    prompt_field(
        "EMAIL_PASSWORD",
        "Gmail App Password  →  myaccount.google.com/apppasswords",
        secret=True,
    )
    prompt_field("NEWSAPI_KEY", "NewsAPI key  →  https://newsapi.org")

    write_env(existing)
    ok("config/.env saved")


# ─────────────────────────────────────────────
#  STEP 5 — contacts.csv
# ─────────────────────────────────────────────
def setup_contacts():
    header("STEP 5 — WhatsApp Contacts (contacts.csv)")

    csv_path = os.path.join(ROOT, "contacts.csv")

    if os.path.exists(csv_path):
        ok("contacts.csv already exists — skipping")
        return

    print()
    print(f"  {DIM}Add contacts for the WhatsApp skill.{RESET}")
    print(f"  {DIM}Phone must be in international format: +14031234567{RESET}")
    print(f"  {DIM}Press Enter with no name to finish.{RESET}")
    print()

    rows = []
    while True:
        name = ask("Contact name (or Enter to finish)").strip()
        if not name:
            break
        phone = ask(f"Phone for {name}  (e.g. +14031234567)").strip()
        if phone:
            rows.append((name, phone))

    with open(csv_path, "w") as f:
        f.write("Name,Phone\n")
        for name, phone in rows:
            f.write(f"{name},{phone}\n")

    if rows:
        ok(f"contacts.csv created with {len(rows)} contact(s)")
    else:
        ok("contacts.csv created (empty — add contacts anytime)")


# ─────────────────────────────────────────────
#  STEP 5.5 — Biometric face login
# ─────────────────────────────────────────────
def setup_biometrics():
    header("STEP 5.5 — Biometric Face Login")

    print()
    print(f"  JARVIS can recognize your face to authenticate login.")
    print(
        f"  {DIM}Uses your webcam. All data stays local — nothing is uploaded.{RESET}"
    )
    print()

    choice = ask("Set up face login now? (y/n)", "n").lower()
    if choice != "y":
        info("Skipping. Say 'register' inside JARVIS anytime to set it up later.")
        return

    # Check opencv contrib
    try:
        import cv2

        if not hasattr(cv2, "face"):
            err("opencv-contrib-python not installed.")
            err("Fix: pip install opencv-contrib-python")
            return
    except ImportError:
        err("cv2 not found. Fix: pip install opencv-contrib-python")
        return

    # Check webcam
    import cv2

    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        err("Could not open webcam. Check your camera and try again.")
        cap.release()
        return
    cap.release()
    ok("Webcam found")

    # Auto-fix opencv conflict
    info("Checking for opencv package conflict...")
    try:
        import cv2

        cv2.face.LBPHFaceRecognizer_create()
        ok("opencv-contrib-python working correctly")
    except AttributeError:
        warn("opencv conflict detected — fixing automatically...")
        run(
            [
                sys.executable,
                "-m",
                "pip",
                "uninstall",
                "opencv-python",
                "opencv-contrib-python",
                "-y",
            ]
        )
        if pip_install(["opencv-contrib-python==4.8.1.78"]):
            ok("opencv-contrib-python reinstalled cleanly")
            import importlib
            import cv2

            importlib.reload(cv2)
        else:
            err("Could not fix opencv. Run manually:")
            err("  pip uninstall opencv-python opencv-contrib-python -y")
            err("  pip install opencv-contrib-python==4.8.1.78")
            return

    print()
    print(f"  {CYAN}Instructions:{RESET}")
    print(f"  • Look directly at the camera")
    print(f"  • Keep your face centred and well-lit")
    print(f"  • The system will capture 50 samples — hold still for ~5 seconds")
    print()
    input(f"  {CYAN}?{RESET}  Press Enter when ready to start capture...")
    print()

    HAAR_XML = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    FACE_DATA_PATH = os.path.join(ROOT, "models", "biometrics", "face_model.yml")

    detector = cv2.CascadeClassifier(HAAR_XML)
    recognizer = cv2.face.LBPHFaceRecognizer_create()

    cap = cv2.VideoCapture(0)
    faces_data = []
    labels = []
    collected = 0

    print(f"  {DIM}Capturing...{RESET}")

    for _ in range(300):
        ret, frame = cap.read()
        if not ret:
            continue
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        detected = detector.detectMultiScale(gray, 1.3, 5)
        for x, y, w, h in detected:
            face_roi = cv2.resize(gray[y : y + h, x : x + w], (200, 200))
            faces_data.append(face_roi)
            labels.append(1)
            collected += 1
        print(f"\r  Samples collected: {collected}/50", end="", flush=True)
        if collected >= 50:
            break

    cap.release()
    print()

    if collected < 10:
        err(f"Not enough face samples captured ({collected}/50).")
        err("Make sure your face is fully visible and the room is well-lit.")
        return

    recognizer.train(faces_data, np.array(labels))
    recognizer.save(FACE_DATA_PATH)
    ok(f"Face registered → face_model.yml  ({collected} samples captured)")
    ok("Say 'login' inside JARVIS to authenticate with your face.")

    env = read_env()
    env["BIOMETRICS_ENABLED"] = "true"
    write_env(env)


# ─────────────────────────────────────────────
#  STEP 6 — LLM setup (local or API)
# ─────────────────────────────────────────────
def setup_llm():
    header("STEP 6 — AI Brain (LLM)")

    print()
    print(f"  How should JARVIS think?\n")
    print(
        f"  {CYAN}[1]{RESET} Local LLM  — runs on your machine, no API key, needs ~2 GB disk + decent RAM"
    )
    print(
        f"  {CYAN}[2]{RESET} API        — faster, smarter, needs an API key (free tiers available)\n"
    )

    choice = ask("Choose (1 or 2)", "1")

    env = read_env()

    # ── LOCAL ─────────────────────────────────────────────────────────────
    if choice == "1":
        env["LLM_MODE"] = "local"

        model_dir = os.path.join(ROOT, "models")
        model_file = os.path.join(model_dir, "Llama-3.2-3B-Instruct-Q4KM.gguf")

        if os.path.exists(model_file):
            size_gb = os.path.getsize(model_file) / (1024**3)
            ok(f"Model already exists ({size_gb:.1f} GB) — skipping download")
            write_env(env)
            return

        os.makedirs(model_dir, exist_ok=True)
        print()
        warn(
            "The model file is ~2 GB. Make sure you have space and a stable connection."
        )
        dl = ask("Download now? (y/n)", "y").lower()

        if dl != "y":
            warn("Skipping. Run  python scripts/downloadmodel.py  later.")
            warn("JARVIS won't respond to 'ask' commands until the model is present.")
            write_env(env)
            return

        script = os.path.join(ROOT, "scripts", "downloadmodel.py")
        if not os.path.exists(script):
            warn("scripts/downloadmodel.py not found.")
            warn(
                "Download manually: https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF"
            )
            write_env(env)
            return

        info("Downloading model — this will take a while...")
        success, _, stderr = run([sys.executable, script])
        if success and os.path.exists(model_file):
            ok("Model downloaded successfully")
        else:
            err(f"Download failed:\n{stderr}")
            warn("Try again: python scripts/downloadmodel.py")

        write_env(env)

    # ── API ───────────────────────────────────────────────────────────────
    elif choice == "2":
        env["LLM_MODE"] = "api"

        providers = {
            "1": (
                "openai",
                "OpenAI (gpt-4o-mini)",
                "https://platform.openai.com/api-keys",
                "gpt-4o-mini",
                ["openai"],
            ),
            "2": (
                "gemini",
                "Google Gemini (gemini-2.0-flash)",
                "https://aistudio.google.com/app/apikey",
                "gemini-2.0-flash",
                ["google-generativeai"],
            ),
            "3": (
                "anthropic",
                "Anthropic Claude (haiku)",
                "https://console.anthropic.com/settings/keys",
                "claude-3-5-haiku-20241022",
                ["anthropic"],
            ),
            "4": (
                "groq",
                "Groq — llama-3.3-70b (free tier)",
                "https://console.groq.com/keys",
                "llama-3.3-70b-versatile",
                ["groq"],
            ),
        }

        print()
        for num, (_, label, url, _, _) in providers.items():
            print(f"  {CYAN}[{num}]{RESET} {label}")
            print(f"       {DIM}Get key: {url}{RESET}")
            print()

        pnum = ask("Choose provider (1-4)", "4")
        if pnum not in providers:
            warn("Invalid — defaulting to Groq")
            pnum = "4"

        provider_id, provider_label, key_url, default_model, sdks = providers[pnum]
        env["LLM_API_PROVIDER"] = provider_id

        print()
        info(f"Get your key at: {key_url}")
        api_key = ask(f"{provider_label} API key")
        if api_key:
            env["LLM_API_KEY"] = api_key
            ok("API key saved")
        else:
            warn("No key entered. Set LLM_API_KEY in config/.env later.")

        model = ask("Model name (Enter for default)", default_model)
        env["LLM_API_MODEL"] = model

        info(f"Installing {provider_id} SDK...")
        if pip_install(sdks):
            ok(f"{provider_id} SDK installed")
        else:
            warn(f"Could not install SDK — run: pip install {' '.join(sdks)}")

        write_env(env)
        ok(f"LLM mode → API  ({provider_label} / {model})")

    else:
        warn("Invalid choice — skipping. Set LLM_MODE in config/.env manually.")


# ─────────────────────────────────────────────
#  STEP 7 — Final verification
# ─────────────────────────────────────────────
def verify():
    header("STEP 7 — Final Verification")

    file_checks = {
        "frontend/dist/index.html": "Frontend build",
        "config/.env": ".env config",
        "contacts.csv": "contacts.csv",
        "requirements.txt": "requirements.txt",
    }

    all_good = True
    for rel_path, label in file_checks.items():
        full = os.path.join(ROOT, rel_path)
        if os.path.exists(full):
            ok(label)
        else:
            warn(f"{label} missing  ({rel_path})")
            all_good = False

    import_checks = [
        ("webview", "pywebview"),
        ("speech_recognition", "SpeechRecognition"),
        ("pyttsx3", "pyttsx3"),
        ("cv2", "opencv-contrib-python"),
        ("selenium", "selenium"),
        ("pywhatkit", "pywhatkit"),
    ]

    print()
    for module, pkg_name in import_checks:
        try:
            __import__(module)
            ok(pkg_name)
        except ImportError:
            warn(f"{pkg_name} not importable — pip install {pkg_name}")
            all_good = False

    try:
        import pyaudio

        ok("pyaudio (voice input)")
    except ImportError:
        warn("pyaudio missing — voice input disabled")
        if IS_WIN:
            warn("  Fix: pip install pipwin && pipwin install pyaudio")

    model = os.path.join(ROOT, "models", "Llama-3.2-3B-Instruct-Q4KM.gguf")
    face = os.path.join(ROOT, "models", "biometrics", "face_model.yml")

    if os.path.exists(model):
        ok("LLM model file")
    else:
        env = read_env()
        if env.get("LLM_MODE") == "api":
            ok("LLM mode → API (no model file needed)")
        else:
            warn("LLM model not found — run: python scripts/downloadmodel.py")

    if os.path.exists(face):
        ok("Face data (face_model.yml)")
    else:
        info("No face data — say 'register' in JARVIS to set up face login")

    return all_good


# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────
def main():
    os.system("cls" if IS_WIN else "clear")

    print(
        f"""
{BOLD}{CYAN}
    ██╗ █████╗ ██████╗ ██╗   ██╗██╗███████╗
    ██║██╔══██╗██╔══██╗██║   ██║██║██╔════╝
    ██║███████║██████╔╝██║   ██║██║███████╗
██  ██║██╔══██║██╔══██╗╚██╗ ██╔╝██║╚════██║
╚█████╔╝██║  ██║██║  ██║ ╚████╔╝ ██║███████║
 ╚════╝ ╚═╝  ╚═╝╚═╝  ╚═╝  ╚═══╝  ╚═╝╚══════╝
{RESET}
{DIM}  Setup Script — run once after cloning{RESET}
"""
    )

    check_python()
    install_python_deps()
    build_frontend()
    configure_env()
    setup_contacts()
    setup_biometrics()
    setup_llm()
    all_ok = verify()

    print()
    if all_ok:
        print(f"{BOLD}{GREEN}  ✓  Setup complete!{RESET}")
    else:
        print(
            f"{BOLD}{YELLOW}  ⚠  Setup done with warnings — fix anything flagged above.{RESET}"
        )

    print(f"\n  {DIM}Launch JARVIS from the project root:{RESET}")
    print(f"  {CYAN}  python webviewmain.py{RESET}\n")


if __name__ == "__main__":
    main()
